# Use a Python base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Install necessary dependencies including git
RUN apt-get update && apt-get install -y git

# Copy the contents of the project to the /app directory
COPY . .

# Ensure the entrypoint script exists and is executable
RUN chmod +x .github/scripts/entrypoint.sh

# Set the entrypoint to the entrypoint script
ENTRYPOINT ["/.github/scripts/entrypoint.sh"]
